//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageOfComputting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Teacher_Name { get; set; }
        public string Department { get; set; }
        public string Level { get; set; }
        public string Semester { get; set; }
        public string LecturerLnk { get; set; }
        public string ExameLnk { get; set; }
        public string CourseLnk { get; set; }
        public string ImgBG { get; set; }
    }
}
